### ISSUE TITLE
The dictionary list does not reflect the selected dictionaries in "Options"

### ISSUE THREAD

**Issue by aquastripe** [pMan/Lookup-for-chrome#8]
![](https://github.com/pMan/Lookup-for-chrome/assets/73936909/cb02cc42-c5d2-4cdf-8b59-69fe92e02473)

Here are the selected dictionaries.

![](https://github.com/pMan/Lookup-for-chrome/assets/73936909/e986c277-dd3a-43ac-91a3-4ce2159ccb03)

But the list shows the unselected ones, e.g. "The Free Dictionary". I confirmed that I pressed the "Save" button.

**Comment by pMan** [comment]
@aquastripe - issue fixed in version 2.5.

**Comment by aquastripe** [comment]
This issue is back. 

![Screenshot 2024-11-01 014829](https://github.com/user-attachments/assets/5d4b3e40-d9d7-4ce2-83e1-e2b9911c3c87)

**Comment by pMan** [comment]
> This issue is back.
> 
> ![Screenshot 2024-11-01 014829](https://private-user-images.githubusercontent.com/73936909/382066572-5d4b3e40-d9d7-4ce2-83e1-e2b9911c3c87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzE1NTgsIm5iZiI6MTczMTAzMTI1OCwicGF0aCI6Ii83MzkzNjkwOS8zODIwNjY1NzItNWQ0YjNlNDAtZDlkNy00Y2UyLTgzZTEtZTJiOTkxMWMzYzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDAyMDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NWI1MDVjZjM2MzdlOTE2MjllMzVkOGE2YmExMTBjMWZmY2NkZTIwMDNjNTc0YjAwZjg0MmRkMDdiOWNlMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T5EOiO08y-5VsYb1FRpfvXk69O2cGOS5WxRoJKAwjac)

Are you seeing this behaviour after a reinstall of the extension?
Are you using version 2.5?
Can you please provide the steps to recreate the issue?

**Comment by aquastripe** [comment]
> > This issue is back.
> > ![Screenshot 2024-11-01 014829](https://private-user-images.githubusercontent.com/73936909/382066572-5d4b3e40-d9d7-4ce2-83e1-e2b9911c3c87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzE1NTgsIm5iZiI6MTczMTAzMTI1OCwicGF0aCI6Ii83MzkzNjkwOS8zODIwNjY1NzItNWQ0YjNlNDAtZDlkNy00Y2UyLTgzZTEtZTJiOTkxMWMzYzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDAyMDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NWI1MDVjZjM2MzdlOTE2MjllMzVkOGE2YmExMTBjMWZmY2NkZTIwMDNjNTc0YjAwZjg0MmRkMDdiOWNlMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T5EOiO08y-5VsYb1FRpfvXk69O2cGOS5WxRoJKAwjac)
> 
> Are you seeing this behaviour after a reinstall of the extension? Are you using version 2.5? Can you please provide the steps to recreate the issue?

1. The version is 2.5 indeed.
2. I followed your instructions to reinstall the extension and fixed the issue.

Thank you very much for your help! Although I don't know what the cause of this issue is.
